# Generated by Django 2.2.5 on 2019-09-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailtemplates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplates',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
