# Generated by Django 2.2.5 on 2019-09-21 07:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmsPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page_name', models.CharField(max_length=255)),
                ('page_title', models.CharField(max_length=255)),
                ('slug', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'CmsPage',
                'db_table': 'cmspages',
            },
        ),
        migrations.CreateModel(
            name='CmsPageDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language_code', models.CharField(db_index=True, max_length=20)),
                ('page_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cms_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmspages.CmsPage')),
            ],
            options={
                'verbose_name_plural': 'CmsPageDescription',
                'db_table': 'cmspage_descriptions',
            },
        ),
    ]
