# Generated by Django 2.2.5 on 2020-01-07 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_currencypriceinusd'),
    ]

    operations = [
        migrations.CreateModel(
            name='currencyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(blank=True, max_length=255, null=True)),
                ('to_currency', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'currency_rate',
            },
        ),
        migrations.DeleteModel(
            name='currencyPriceInUsd',
        ),
    ]
