# Generated by Django 2.2.5 on 2019-09-21 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('lang_code', models.CharField(db_index=True, max_length=100)),
                ('folder_code', models.CharField(db_index=True, max_length=100)),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='LanguageSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('msgid', models.CharField(db_index=True, max_length=255)),
                ('locale', models.CharField(db_index=True, max_length=255)),
                ('msgstr', models.CharField(max_length=255)),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'language_settings',
            },
        ),
    ]
