# Generated by Django 3.0.4 on 2020-04-29 07:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page_name', models.CharField(db_index=True, max_length=255)),
                ('page_slug', models.CharField(blank=True, max_length=255)),
                ('block_name', models.CharField(max_length=255)),
                ('slug', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('image', models.CharField(blank=True, max_length=255)),
                ('block_order', models.IntegerField(default=0)),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Block',
                'db_table': 'blocks',
            },
        ),
        migrations.CreateModel(
            name='BlockDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language_code', models.CharField(db_index=True, max_length=20)),
                ('block_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blocks.Block')),
            ],
            options={
                'verbose_name_plural': 'BlockDescription',
                'db_table': 'block_descriptions',
            },
        ),
    ]
