# Generated by Django 2.2.5 on 2019-09-21 09:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DropDownManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('dropdown_type', models.CharField(db_index=True, max_length=255)),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'DropDownManager',
                'db_table': 'dropdown_managers',
            },
        ),
        migrations.CreateModel(
            name='DropDownManagerDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language_code', models.CharField(db_index=True, max_length=20)),
                ('name', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dropdown_manger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropdownmanger.DropDownManager')),
            ],
            options={
                'verbose_name_plural': 'DropDownManagerDescription',
                'db_table': 'dropdown_manager_descriptions',
            },
        ),
    ]
