# Generated by Django 2.2.5 on 2019-09-21 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dropdownmanger', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='married_status',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='parmanete_address',
            new_name='address_line_2',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='anniversary_date',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='department',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='joining_date',
            new_name='eyes',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='middle_name',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='team',
            new_name='hair',
        ),
        migrations.RemoveField(
            model_name='user',
            name='official_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skype_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='temporary_address',
        ),
        migrations.AddField(
            model_name='user',
            name='amazon_wishlist_link',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='previous_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='previous_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='private_snapchat_link',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='public_instagram_link',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='public_snapchat_link',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skype_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube_video_url',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='ModelImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'model_images',
            },
        ),
        migrations.CreateModel(
            name='ModelCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dropdown_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dropdownmanger.DropDownManager')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'model_categories',
            },
        ),
    ]
