# Generated by Django 2.2.5 on 2019-09-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190923_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='validate_string',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
