# Generated by Django 2.2.5 on 2019-09-25 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190923_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_account', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('is_enabled', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'model_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='ModelSubscriptionPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(blank=True, max_length=255, null=True)),
                ('offer_period_time', models.CharField(blank=True, max_length=255, null=True)),
                ('offer_period_type', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_discount_enabled', models.IntegerField(default=0)),
                ('discount', models.CharField(blank=True, max_length=255, null=True)),
                ('from_discount_date', models.CharField(blank=True, max_length=255, null=True)),
                ('to_discount_date', models.CharField(blank=True, max_length=255, null=True)),
                ('is_permanent_discount', models.IntegerField(default=0)),
                ('is_apply_to_rebills', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model_subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.ModelSubscriptions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'model_subscription_plans',
            },
        ),
    ]
