# Generated by Django 2.2.5 on 2019-09-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_modelsubscriptionplans_modelsubscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='government_id_back_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='government_id_expiration_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='government_id_front_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='government_id_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_next_to_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_next_to_id_with_dated_paper',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
