# Generated by Django 2.2.5 on 2019-09-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190925_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
