# Generated by Django 2.2.5 on 2019-10-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='best_known_for',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
