# Generated by Django 2.2.5 on 2019-10-10 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_best_known_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelNotificationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_subscription_purchased', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_expires', models.CharField(blank=True, max_length=255, null=True)),
                ('received_tip', models.CharField(blank=True, max_length=255, null=True)),
                ('subscriber_updates_snapchat_name', models.CharField(blank=True, max_length=255, null=True)),
                ('detects_login_unverified_device', models.CharField(blank=True, max_length=255, null=True)),
                ('detects_unsuccessful_login', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'model_notification_settings',
            },
        ),
    ]
