# Generated by Django 2.2.5 on 2019-10-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_modelnotificationsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelnotificationsetting',
            name='detects_login_unverified_device',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modelnotificationsetting',
            name='detects_unsuccessful_login',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modelnotificationsetting',
            name='new_subscription_purchased',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modelnotificationsetting',
            name='received_tip',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modelnotificationsetting',
            name='subscriber_updates_snapchat_name',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modelnotificationsetting',
            name='subscription_expires',
            field=models.IntegerField(default=0),
        ),
    ]
