# Generated by Django 2.2.5 on 2019-10-14 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20191010_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_name', models.CharField(blank=True, max_length=255, null=True)),
                ('post_code', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('model_subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.ModelSubscriptions')),
                ('plan_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.ModelSubscriptionPlans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_subscription_plans',
            },
        ),
    ]
