# Generated by Django 2.2.5 on 2019-10-14 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_usersubscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='model_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
