# Generated by Django 2.2.5 on 2019-10-15 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_privatefeedmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatefeedmodel',
            name='schedule_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
