# Generated by Django 2.2.5 on 2019-10-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20191015_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatefeedmodel',
            name='status',
            field=models.CharField(default='draft', max_length=50),
        ),
    ]
