# Generated by Django 2.2.5 on 2019-10-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20191015_1015'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='privatefeedmodel',
            table='private_feeds',
        ),
    ]
