# Generated by Django 2.2.5 on 2019-10-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20191015_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='subscription_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
