# Generated by Django 2.2.5 on 2019-10-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_usersubscriptionplan_subscription_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatefeedmodel',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='privatefeedmodel',
            name='schedule_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
