# Generated by Django 2.2.5 on 2019-10-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20191018_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsubscriptionplans',
            name='offer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
