# Generated by Django 2.2.5 on 2019-12-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_modelsubscriptionplans_offer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='transaction_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
