# Generated by Django 2.2.5 on 2019-12-05 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_usersubscriptionplan_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.IntegerField(db_index=True, default=0)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='success', max_length=50)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.ModelSubscriptionPlans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transaction_history',
            },
        ),
    ]
