# Generated by Django 2.2.5 on 2019-12-05 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_transactionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.UserSubscriptionPlan'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
