# Generated by Django 2.2.5 on 2019-12-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20191205_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='plan',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
