# Generated by Django 2.2.5 on 2019-12-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20191206_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
