# Generated by Django 2.2.5 on 2019-12-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_transactionhistory_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipme',
            name='transaction_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
