# Generated by Django 2.2.5 on 2019-12-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_modelviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
    ]
