# Generated by Django 2.2.5 on 2019-12-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_user_total_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='highest_discount',
            field=models.IntegerField(default=0),
        ),
    ]
