# Generated by Django 2.2.5 on 2019-12-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_user_highest_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='featured_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
