# Generated by Django 2.2.5 on 2019-12-19 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_user_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
