# Generated by Django 2.2.5 on 2019-12-19 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_usersubscriptionplan_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='model_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.ModelSubscriptions'),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.ModelSubscriptionPlans'),
        ),
    ]
