# Generated by Django 2.2.5 on 2019-12-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20191219_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='tip_id',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
