# Generated by Django 2.2.5 on 2019-12-19 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_transactionhistory_tip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
