# Generated by Django 2.2.5 on 2019-12-20 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_transactionhistory_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='tip_id',
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='tips',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.TipMe'),
        ),
    ]
