# Generated by Django 2.2.5 on 2019-12-31 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20191231_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.ModelSubscriptionPlans'),
        ),
    ]
