# Generated by Django 2.2.5 on 2019-12-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20191231_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsubscriptionplans',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
