# Generated by Django 2.2.5 on 2019-12-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20191231_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsubscriptions',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
