# Generated by Django 2.2.5 on 2020-01-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_modelsubscriptions_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsubscriptionplans',
            name='price_in_usd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
