# Generated by Django 2.2.5 on 2020-01-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_modelsubscriptionplans_price_in_usd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelsubscriptionplans',
            name='price_in_usd',
        ),
        migrations.AddField(
            model_name='tipme',
            name='price_in_usd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='price_in_usd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
