# Generated by Django 2.2.5 on 2020-01-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20200102_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsubscriptionplans',
            name='discounted_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
