# Generated by Django 2.2.5 on 2020-01-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_modelsubscriptionplans_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='price_in_usd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
