# Generated by Django 2.2.5 on 2020-01-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_transactionhistory_price_in_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
