# Generated by Django 2.2.5 on 2020-01-08 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_user_default_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipme',
            old_name='price_in_usd',
            new_name='price_in_model_currency',
        ),
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='price_in_usd',
            new_name='price_in_model_currency',
        ),
        migrations.RenameField(
            model_name='usersubscriptionplan',
            old_name='price_in_usd',
            new_name='price_in_model_currency',
        ),
    ]
