# Generated by Django 2.2.5 on 2020-01-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_auto_20200108_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='commission_amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
