# Generated by Django 2.2.5 on 2020-01-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_payout_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rank_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
