# Generated by Django 2.2.5 on 2020-01-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_accountdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='plan_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
