# Generated by Django 2.2.5 on 2020-01-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_usersubscriptionplan_plan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriptionplan',
            name='plan_status',
            field=models.CharField(blank=True, default='active', max_length=255, null=True),
        ),
    ]
