# Generated by Django 2.2.5 on 2020-01-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_authorizedevices'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsubscriptionplans',
            name='model_status',
            field=models.IntegerField(default=0),
        ),
    ]
