# Generated by Django 2.2.5 on 2020-01-28 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_auto_20200127_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriptionplan',
            name='model_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userparent', to=settings.AUTH_USER_MODEL),
        ),
    ]
