# Generated by Django 2.2.5 on 2020-01-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_auto_20200128_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forgot_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
