# Generated by Django 2.2.5 on 2020-02-03 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_user_forgot_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='forgot_password',
            new_name='forgot_password_string',
        ),
    ]
