# Generated by Django 2.2.5 on 2020-02-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_auto_20200203_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='tip_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
