# Generated by Django 2.2.5 on 2020-03-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_auto_20200311_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signup_from',
            field=models.IntegerField(default=0),
        ),
    ]
