# Generated by Django 2.2.5 on 2020-03-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_auto_20200312_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='signup_from',
        ),
    ]
