# Generated by Django 2.2.5 on 2020-03-12 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_remove_user_signup_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signup_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
