# Generated by Django 3.0.4 on 2020-03-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0074_user_total_subscriber_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscription_enabled',
            field=models.IntegerField(default=1),
        ),
    ]
