# Generated by Django 3.0.4 on 2020-03-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_user_is_subscription_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_with_model',
            field=models.IntegerField(default=0),
        ),
    ]
