# Generated by Django 3.0.4 on 2020-03-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_user_login_with_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.IntegerField(default=1),
        ),
    ]
