# Generated by Django 3.0.4 on 2020-04-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0077_auto_20200330_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsubscriptionplans',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
