# Generated by Django 3.0.4 on 2020-04-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0078_auto_20200402_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsubscriptionplans',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
