# Generated by Django 3.0.4 on 2020-05-01 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0079_auto_20200402_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='user_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.UserSubscriptionPlan'),
        ),
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='plan_validity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
