# Generated by Django 3.0.4 on 2020-05-01 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0081_auto_20200501_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='user_subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.UserSubscriptionPlan'),
        ),
    ]
