# Generated by Django 3.0.4 on 2020-05-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_auto_20200501_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_homepage_profile',
            field=models.CharField(blank=True, default=1, max_length=255, null=True),
        ),
    ]
