# Generated by Django 3.0.4 on 2020-05-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0085_user_is_homepage_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetails',
            name='method',
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='bacs_method',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='cheque_method',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='paypal_method',
            field=models.IntegerField(default=0),
        ),
    ]
