# Generated by Django 3.0.4 on 2020-05-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0086_auto_20200505_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetails',
            name='is_saved',
            field=models.IntegerField(default=0),
        ),
    ]
