# Generated by Django 3.0.4 on 2020-05-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0087_accountdetails_is_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
