# Generated by Django 3.0.4 on 2020-05-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0088_payout_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_private_feed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='main_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
