# Generated by Django 2.2.5 on 2020-05-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0089_auto_20200512_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsubscriptionplans',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='modelsubscriptionplans',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
