# Generated by Django 2.2.5 on 2020-05-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0090_auto_20200519_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='discounted_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='from_discount_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='is_apply_to_rebills',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='is_discount_enabled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='is_permanent_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='offer_period_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='offer_period_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='planprice',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='to_discount_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='transaction_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscriptionplan',
            name='plan_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
