# Generated by Django 2.2.5 on 2020-05-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0091_auto_20200519_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriptionplan',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersubscriptionplan',
            name='planprice',
            field=models.IntegerField(default=0),
        ),
    ]
