# Generated by Django 2.2.5 on 2020-05-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0093_auto_20200519_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriptionplan',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
