# Generated by Django 2.2.5 on 2020-05-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0094_auto_20200519_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='is_subscription_cancelled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='is_subscription_cancelled',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modelsubscriptionplans',
            name='discounted_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usersubscriptionplan',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usersubscriptionplan',
            name='discounted_price',
            field=models.FloatField(default=0),
        ),
    ]
