# Generated by Django 2.2.5 on 2020-05-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0095_auto_20200520_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='feedback',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='stay_connected',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
