# Generated by Django 2.2.5 on 2020-05-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0096_auto_20200520_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='plan',
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='plan_id',
            field=models.IntegerField(default=0),
        ),
    ]
