# Generated by Django 2.2.5 on 2020-05-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0097_auto_20200520_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='best_known_for',
            field=models.TextField(blank=True, null=True),
        ),
    ]
