# Generated by Django 3.0.4 on 2020-05-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0098_auto_20200527_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdetails',
            old_name='country',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='accountdetails',
            old_name='iban',
            new_name='beneficiary_address',
        ),
        migrations.RenameField(
            model_name='accountdetails',
            old_name='pay_to',
            new_name='beneficiary_name',
        ),
        migrations.RemoveField(
            model_name='accountdetails',
            name='bacs_method',
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='institution_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='paypal_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='transit_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='wire_method',
            field=models.CharField(default='wire', max_length=255),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='cheque_method',
            field=models.CharField(default='cheque', max_length=255),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='paypal_method',
            field=models.CharField(default='paypal', max_length=255),
        ),
    ]
