# Generated by Django 3.0.4 on 2020-05-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0099_auto_20200529_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='cheque_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='paypal_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
