# Generated by Django 2.2.5 on 2020-06-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0100_auto_20200529_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='commission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='payment_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='user_subscription_plan_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
