# Generated by Django 3.0.7 on 2020-06-09 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0100_auto_20200529_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_homepage_profile',
        ),
    ]
