# Generated by Django 2.2.5 on 2020-06-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0101_auto_20200601_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscriptionplan',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='payment_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
