# Generated by Django 3.0.7 on 2020-06-09 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0101_remove_user_is_homepage_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_private_feed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='main_image',
        ),
    ]
