# Generated by Django 2.2.5 on 2020-06-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0102_auto_20200601_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='join_commission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payout',
            name='join_gross_revenue',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payout',
            name='join_net_revenue',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payout',
            name='rebill_commission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payout',
            name='rebill_gross_revenue',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payout',
            name='rebill_net_revenue',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payout',
            name='tip_commission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payout',
            name='tip_gross_revenue',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payout',
            name='tip_net_revenue',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payout',
            name='commission_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payout',
            name='gross_revenue',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payout',
            name='net_revenue',
            field=models.FloatField(default=0),
        ),
    ]
