# Generated by Django 2.2.5 on 2020-06-03 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0103_auto_20200603_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
