# Generated by Django 3.0.7 on 2020-06-12 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0102_auto_20200609_1814'),
        ('users', '0104_payout_payment_date'),
    ]

    operations = [
    ]
