# Generated by Django 3.0.7 on 2020-06-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0105_merge_20200612_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_homepage_profile',
            field=models.CharField(blank=True, default=1, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_private_feed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='main_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
