# Generated by Django 3.0.7 on 2020-06-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0106_auto_20200612_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='is_flaged',
            field=models.IntegerField(default=0),
        ),
    ]
