# Generated by Django 3.0.7 on 2020-06-12 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0107_usersubscriptionplan_is_flaged'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='subscription_cancelled_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='subscription_cancelled_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
