# Generated by Django 3.0.7 on 2020-06-15 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0108_auto_20200612_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetails',
            name='is_saved',
        ),
        migrations.RemoveField(
            model_name='accountdetails',
            name='minimum_payout',
        ),
    ]
