# Generated by Django 3.0.7 on 2020-06-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0109_auto_20200615_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdetails',
            old_name='wire_method',
            new_name='payment_method',
        ),
        migrations.RemoveField(
            model_name='accountdetails',
            name='cheque_method',
        ),
        migrations.RemoveField(
            model_name='accountdetails',
            name='paypal_method',
        ),
    ]
