# Generated by Django 3.0.7 on 2020-06-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0110_auto_20200616_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
