# Generated by Django 2.2.5 on 2020-06-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0111_auto_20200616_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatefeedmodel',
            name='is_converted',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='privatefeedmodel',
            name='uploaded_file_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
