# Generated by Django 3.0.7 on 2020-06-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0112_auto_20200618_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
