# Generated by Django 3.0.7 on 2020-06-22 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0113_auto_20200622_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdetails',
            old_name='account_number',
            new_name='account_name',
        ),
        migrations.RenameField(
            model_name='accountdetails',
            old_name='beneficiary_address',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='accountdetails',
            old_name='beneficiary_name',
            new_name='iban',
        ),
        migrations.RenameField(
            model_name='accountdetails',
            old_name='institution_number',
            new_name='minimum_payout',
        ),
        migrations.RenameField(
            model_name='accountdetails',
            old_name='memo',
            new_name='pay_to',
        ),
        migrations.RemoveField(
            model_name='accountdetails',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='accountdetails',
            name='transit_number',
        ),
    ]
