# Generated by Django 3.0.7 on 2020-06-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0114_auto_20200622_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdetails',
            old_name='account_name',
            new_name='cheque_email',
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
