# Generated by Django 3.0.7 on 2020-06-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0116_additionallinks'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='additionallinks',
            table='model_additional_links',
        ),
    ]
