# Generated by Django 3.0.7 on 2020-06-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0117_auto_20200623_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriptionplan',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
