# Generated by Django 3.0.7 on 2020-06-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0118_auto_20200625_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='is_tick_marked',
            field=models.IntegerField(default=0),
        ),
    ]
