# Generated by Django 3.0.7 on 2020-07-06 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0119_usersubscriptionplan_is_tick_marked'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayErrors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_name', models.CharField(blank=True, max_length=255, null=True)),
                ('post_code', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField(default=0)),
                ('price_in_model_currency', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_status', models.CharField(blank=True, default='active', max_length=255, null=True)),
                ('plan_validity', models.CharField(blank=True, max_length=255, null=True)),
                ('feedback', models.CharField(blank=True, max_length=255, null=True)),
                ('stay_connected', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_type', models.CharField(blank=True, max_length=255, null=True)),
                ('offer_period_time', models.CharField(blank=True, max_length=255, null=True)),
                ('offer_period_type', models.CharField(blank=True, max_length=255, null=True)),
                ('planprice', models.FloatField(default=0)),
                ('discounted_price', models.FloatField(default=0)),
                ('is_discount_enabled', models.IntegerField(default=0)),
                ('is_subscription_cancelled', models.IntegerField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('from_discount_date', models.CharField(blank=True, max_length=255, null=True)),
                ('to_discount_date', models.CharField(blank=True, max_length=255, null=True)),
                ('is_permanent_discount', models.IntegerField(default=0)),
                ('is_apply_to_rebills', models.IntegerField(default=0)),
                ('user_subscription_plan_description', models.TextField(blank=True, null=True)),
                ('is_flaged', models.IntegerField(default=0)),
                ('subscription_cancelled_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_tick_marked', models.IntegerField(default=0)),
                ('response', models.CharField(blank=True, max_length=255, null=True)),
                ('model_subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.ModelSubscriptions')),
                ('model_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paymentgatewayerrors', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_gateway_errors',
            },
        ),
    ]
