# Generated by Django 3.0.7 on 2020-07-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0120_paymentgatewayerrors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgatewayerrors',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
