# Generated by Django 3.0.7 on 2020-07-06 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0121_auto_20200706_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgatewayerrors',
            name='model_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.ModelSubscriptions'),
        ),
    ]
