# Generated by Django 3.0.7 on 2020-07-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0122_auto_20200706_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewayerrors',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
