# Generated by Django 3.0.7 on 2020-07-07 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0123_paymentgatewayerrors_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionallinks',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
