# Generated by Django 2.2.5 on 2020-07-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0124_auto_20200707_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalizedTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('errors', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'finalized_transactions',
            },
        ),
    ]
