# Generated by Django 2.2.5 on 2020-07-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0125_finalizedtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='offer_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersubscriptionplan',
            name='offer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
