# Generated by Django 2.2.5 on 2020-07-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0126_auto_20200725_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='refunds_commission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payout',
            name='refunds_gross_revenue',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payout',
            name='refunds_net_revenue',
            field=models.FloatField(default=0),
        ),
    ]
