# Generated by Django 2.2.5 on 2019-10-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='body',
            field=models.TextField(),
        ),
    ]
