# Generated by Django 2.2.5 on 2019-10-04 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_subscriber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriber',
            new_name='NewsletterSubscriber',
        ),
        migrations.AlterModelTable(
            name='newslettersubscriber',
            table='newsletter_subscribers',
        ),
    ]
