# Generated by Django 2.2.5 on 2019-10-04 12:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0005_schedulednewsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledNewsletterSubscriber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_newsletters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletters.NewsletterSubscriber')),
            ],
            options={
                'db_table': 'scheduled_newsletter_subscribers',
            },
        ),
    ]
