# Generated by Django 2.2.5 on 2019-10-05 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0006_schedulednewslettersubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulednewslettersubscriber',
            name='scheduled_newsletters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletters.Newsletter'),
        ),
    ]
