# Generated by Django 2.2.5 on 2019-10-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0007_auto_20191005_0448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulednewslettersubscriber',
            old_name='scheduled_newsletters',
            new_name='scheduled_newsletter',
        ),
    ]
