# Generated by Django 2.2.5 on 2019-10-05 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0008_auto_20191005_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulednewslettersubscriber',
            name='scheduled_newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletters.ScheduledNewsletter'),
        ),
    ]
