# Generated by Django 2.2.5 on 2019-10-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0009_auto_20191005_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulednewslettersubscriber',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
