# Generated by Django 2.2.5 on 2020-01-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0010_schedulednewslettersubscriber_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulednewsletter',
            name='is_send',
            field=models.IntegerField(default=0),
        ),
    ]
