# Generated by Django 2.2.5 on 2020-03-04 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0012_newslettersubscriber_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulednewsletter',
            name='mail_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
