# Generated by Django 2.2.5 on 2020-03-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0013_schedulednewsletter_mail_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulednewsletter',
            name='mail_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
