# Generated by Django 2.2.5 on 2020-03-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0014_auto_20200304_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulednewsletter',
            name='mail_on',
        ),
        migrations.AddField(
            model_name='schedulednewslettersubscriber',
            name='mail_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
