# Generated by Django 2.2.5 on 2019-09-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='weigth',
        ),
        migrations.AlterField(
            model_name='settings',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
