# Generated by Django 3.0.4 on 2020-04-29 08:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('is_active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Faqs',
                'db_table': 'faqs',
            },
        ),
        migrations.CreateModel(
            name='FaqDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language_code', models.CharField(db_index=True, max_length=20)),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.Faq')),
            ],
            options={
                'verbose_name_plural': 'FaqDescription',
                'db_table': 'faq_description',
            },
        ),
    ]
