# Generated by Django 2.2.5 on 2020-05-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='pagename',
            field=models.TextField(blank=True, null=True),
        ),
    ]
