"""
Django settings for tfh project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import datetime


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(2kzm&6l=#-yzw0r_hwghh=il!#3q5+v#99gg0y4^3(wjoia90'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	'templatetags.apps.TemplatetagsConfig',
    'apps.dashboard.apps.DashboardConfig',
	'apps.login.apps.LoginConfig',
	'apps.emailtemplates.apps.EmailtemplatesConfig',
	'apps.settings.apps.SettingsConfig',
	'apps.dropdownmanger.apps.DropdownmangerConfig',
	'apps.users.apps.UsersConfig',
    'apps.languages.apps.LanguagesConfig',
    'apps.cmspages.apps.CmspagesConfig',
    'apps.emaillogs.apps.EmaillogsConfig',
    'apps.blocks.apps.BlocksConfig',
    'apps.supports.apps.SupportsConfig',
    'apps.newsletters.apps.NewslettersConfig',
    'apps.modelreport.apps.ModelReportConfig',
    'apps.api.apps.ApiConfig',
    'apps.slider.apps.SliderConfig',
    'apps.payout.apps.PayoutConfig',
    'apps.cron.apps.CronConfig',
    'apps.common.apps.CommonConfig',
    'apps.incomehistory.apps.IncomeHistoryConfig',
    'apps.transactions.apps.TransactionConfig',
	'apps.failedtransactions.apps.FailedTransactionConfig',
	'apps.faq.apps.FaqConfig',
    'rest_framework',
    'corsheaders'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]
CORS_ORIGIN_ALLOW_ALL=True
""" CORS_ORIGIN_WHITELIST = (
    'localhost:3000',
) """

ROOT_URLCONF = 'tfh.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django_settings_export.settings_export',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages'
            ],
        },
    },
]

WSGI_APPLICATION = 'tfh.wsgi.application'

AUTH_USER_MODEL = 'users.User'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'tfh',
        'USER': 'postgres',
        'PASSWORD': 'NITINumang11',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Look for the REST_FRAMEWORK inside the settings.py file

REST_FRAMEWORK = {
    # ...
    
    # inside the Rest framework settings dictionary, add the auth settings
    # Authentication settings
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
    ],

    # inside the Rest framework settings dictionary, add the permission settings
    # Permission settings
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    
    #...
}

# JWT settings
JWT_AUTH = {
    'JWT_ENCODE_HANDLER':
    'rest_framework_jwt.utils.jwt_encode_handler',

    'JWT_DECODE_HANDLER':
    'rest_framework_jwt.utils.jwt_decode_handler',

    'JWT_PAYLOAD_HANDLER':
    'rest_framework_jwt.utils.jwt_payload_handler',

    'JWT_PAYLOAD_GET_USER_ID_HANDLER':
    'rest_framework_jwt.utils.jwt_get_user_id_from_payload_handler',

    'JWT_RESPONSE_PAYLOAD_HANDLER':
    'rest_framework_jwt.utils.jwt_response_payload_handler',

    'JWT_SECRET_KEY': SECRET_KEY,
    'JWT_GET_USER_SECRET_KEY': None,
    'JWT_PUBLIC_KEY': None,
    'JWT_PRIVATE_KEY': None,
    'JWT_ALGORITHM': 'HS256',
    'JWT_VERIFY': True,
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_LEEWAY': 0,
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=1),
    'JWT_AUDIENCE': None,
    'JWT_ISSUER': None,

    'JWT_ALLOW_REFRESH': False,
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=7),

    'JWT_AUTH_HEADER_PREFIX': 'Bearer',
    'JWT_AUTH_COOKIE': None,
}



# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER ='obtechdemo@gmail.com'
EMAIL_HOST_PASSWORD ='Owebest@_1'
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = ( os.path.join(BASE_DIR, 'locale'), )


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static/'),
]

#  google cloud storage for media
from google.oauth2 import service_account
# storage
GS_CREDENTIALS = service_account.Credentials.from_service_account_file(
    os.path.join(BASE_DIR, 'credential.json')
)

# DEFAULT_FILE_STORAGE = 'tfh.gcloud.GoogleCloudMediaFileStorage'
DEFAULT_FILE_STORAGE = 'google.storage.googleCloud.GoogleCloudStorage'
GS_PROJECT_ID = 'prodproject-96024'
GS_BUCKET_NAME = 'my_tfh_local_bucket'
# MEDIA_ROOT = 'images/'
# UPLOAD_ROOT = 'media/uploads/'
# MEDIA_URL = 'https://storage.googleapis.com/{}/'.format(GS_BUCKET_NAME)


MEDIA_URL = 'https://storage.googleapis.com/{}/media/uploads/'.format(GS_BUCKET_NAME)
FRONT_SITE_URL = 'http://127.0.0.1:4211/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# MEDIA_URL = '/media/'

MEDIA_SITE_URL = 'http://127.0.0.1:8000/media/uploads/private_feed_images/'
FRONT_SITE_URL = 'http://127.0.0.1:4211/'
MODEL_IMAGE_URL= MEDIA_URL+"model_images/"
BLOCK_IMAGE_URL= MEDIA_URL+"block_images/"
PAYOUT_IMAGE_URL= MEDIA_URL+"payout_slips/"
PRIVATE_FEED_IMAGE_URL= MEDIA_URL+"private_feed_images/"
SLIDER_IMAGE_URL= MEDIA_URL+"slider_images/"
SETTING_IMAGE_URL = MEDIA_URL+"setting_images/"

NEWSLETTER_CONSTANTS    = [
    'TO_EMAIL','WEBSITE_URL','UNSUBSCRIBE_LINK'
]

PAYMENT_GATEWAY_CREATE_PAYMENT_PATH = 'http://nstfh.stage02.obdemo.com/create-payment'
PAYMENT_GATEWAY_RECURRING_PAYMENT_PATH = 'http://nstfh.stage02.obdemo.com/create-recurring-payment'
#PAYMENT_GATEWAY_CREATE_PAYMENT_PATH = 'https://payment.thefanhomepage.com/create-payment'
#PAYMENT_GATEWAY_RECURRING_PAYMENT_PATH = 'https://payment.thefanhomepage.com/create-recurring-payment'


SOCIALTWITTER_LINK="https://twitter.com/"
SOCIALINSTAGRAM_LINK="https://www.instagram.com/"
SOCIALSNAPCHAT_LINK="https://www.snapchat.com/"
SOCIALWHATSAPP_LINK="https://www.whatsapp.com/"
SOCIALFACEBOOK_LINK="https://www.facebook.com/"
SOCIALPRIVATE_FEED_LINK="https://www.privatefeed.com/"
SITETITLE="The Fan Homepage"
READINGRECORDPERPAGE="10"
SITEWEBSITECOMMISSION="25"

READINGDATE_FORMAT="M-d-Y"
READINGDATE_TIME_FORMAT="M-d-Y, h:i A"

GLOBAL_CONSTANT_CURRENCY = [
    'USD','AUD','GBP','EUR',
]


SITEEMAIL="info@thefanhomepage.com"
SITEADDRESS="586 Edgemont Drive Batavia, OH 45103"
SITEPHONE="08102456587"

SITESHOW_MODEL_LISTING_ON_HOMEPAGE="0"
SITEFLAG="obtechdemo@gmail.com"
SITEMODEL_SIGNUP_EMAIL_TO_ADMIN="owebest01@gmail.com"

SETTINGS_EXPORT = [
    'NEWSLETTER_CONSTANTS','SOCIALTWITTER_LINK','SOCIALINSTAGRAM_LINK','SITETITLE','READINGRECORDPERPAGE','SITEWEBSITECOMMISSION','SOCIALSNAPCHAT_LINK','SOCIALWHATSAPP_LINK','SOCIALPRIVATE_FEED_LINK','SOCIALFACEBOOK_LINK','MODEL_IMAGE_URL','BLOCK_IMAGE_URL','PAYOUT_IMAGE_URL','PRIVATE_FEED_IMAGE_URL','SLIDER_IMAGE_URL','SETTING_IMAGE_URL','PAYOUT_IMAGE_URL'
]

CUSTOMTITLE="heloo custome setting"
CONVERTEDVIDEO="112020/13 (1)1604395301.png"
WIDGETTITLE="112020/35 (2)1604470522.png"
NAMEONE="112020/1604512358342878.png"
DANSETTING="112020/1604512810483329.png"
