# Generated by Django 2.2.5 on 2020-01-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
