from django.urls import path
from .views import LoginView, isFlagedApi, modelSubscriberPlanList, RegisterUsers,UpdateModelSubscriptionPlan, UpdateModelProfileStep1, UpdateModelProfileStep2, ModelPersonalInformation, ModelVerificationInformation, MainProfileImage, PrivateFeedEnable, NewExpiredSubscribers, ListModelCategory, EditPaymentMethodApi, DeActivateAccount, SiteContentImages,ListCountry,ValidateSignupUsers,createSubscriber,FeaturedProfile,allModels,cmsPageView,supportView,aboutView,makeMoneyOne,makeMoneyTwo,verifyAccountView,modelProfile,FaqText ,manageSubscription,followModel,newModels,followingList,deleteImage,manageNotifications,saveUserSubscription,saveUserSubscriptionfinalize,SubscribeNewsletter,PrivateFeed,getSubscriptionList,PublishPrivateFeed,modelPrivateFeed,ListReportReason,ReportReason,getUserSubscriptionPlanList,subscriberModelForYou,cancelledPlan,getUserTransactionList,PayOutHistory,ModelProfileImages,ModelPaymentDetails,ListSettings,DeleteAccount,ModelSubscriptionStatusActive,ModelSubscriptionStatusDeactive, ModelUserSubscribeGraph,BannerSlider, GetSystemIp, unsubscribeNeswletter,ValidateforgotPassword,ResetPassword,BlockText,UserSubscribe, ReferSlugApi,ModelVerificationImages, PaymentProcessing, MasterLogin,editProfile,HomepageProfileApi, isTickMark
from .views2 import TipMeApi,TipMeApifinalize,modelDashboardBiggestFan,modelDashboardTopTenBiggestFan,modelRevenue,modelBasicInfo,modelTransactionHistory,modelPayoutHistory,modelSplitData,modelActiveSubscribers,modelreportedSubscribers,modelExpiredSubscribers,modelNewExpiredSubscribers,ListRevenueGraph, ModelProfileViewGraph, NewExpiredSubscribersGraph,CheckSubscribedPlanDetail

urlpatterns = [
    path("model-category", ListModelCategory.as_view(), name='model-category'),
    path("country", ListCountry.as_view(), name='model-country'),
	path('auth/login', LoginView.as_view(), name="auth-login"),
    path('auth/register', RegisterUsers.as_view(), name="auth-register"),
    path('register', ValidateSignupUsers.as_view(), name="validate-auth-register"),
    path('create-subscriber', createSubscriber.as_view(), name="createSubscriber"),
    path('featured-profile', FeaturedProfile.as_view(), name="featured-profile"),
    path('models', allModels.as_view(), name="models"),
    path('pages', cmsPageView.as_view(), name="pages"),
    path('support', supportView.as_view(), name="support"),
    path('about', aboutView.as_view(), name="about"),
    path('make-money-1', makeMoneyOne.as_view(), name="make-money-1"),
    path('make-money-2', makeMoneyTwo.as_view(), name="make-money-2"),
    path('verify-account', verifyAccountView.as_view(), name="verify-account"),
    path('subscriptions', manageSubscription.as_view(), name="subscriptions"),
    path('save-subscriptions', manageSubscription.as_view(), name="save-subscriptions"),
    path('delete-subscriptions', manageSubscription.as_view(), name="delete-subscriptions"),
    path('edit-profile', editProfile.as_view(), name="edit-profile"),
	#path('save-profile-1', editProfile1.as_view(), name="save-profile-1"),
    path('save-profile', editProfile.as_view(), name="save-profile"),
    path('model-profile', modelProfile.as_view(), name="model-profile"),
    path('follow-model', followModel.as_view(), name="follow-model"),
    path('new-models', newModels.as_view(), name="new-models"),
    path('delete-image', deleteImage.as_view(), name="delete-image"),
    path('notifications-settings', manageNotifications.as_view(), name="notifications-settings"),
    path('save-user-subscription', saveUserSubscription.as_view(), name="save-user-subscription"),
    path('save-user-subscription-finalized', saveUserSubscriptionfinalize.as_view(), name="save-user-subscription-finalized"),
    path('user-subscribe', UserSubscribe.as_view(), name="user-subscribe"),
    path('newsletter-subscribe', SubscribeNewsletter.as_view(), name="newsletter-subscribe"),
    path('add-private-feed', PrivateFeed.as_view(), name="add-private-feed"),
    path('private-feeds', PrivateFeed.as_view(), name="private-feeds"),
    path('edit-private-feed', PrivateFeed.as_view(), name="edit-private-feed"),
    path('delete-private-feed', PrivateFeed.as_view(), name="delete-private-feed"),
    path('publish-private-feed', PublishPrivateFeed.as_view(), name="publish-private-feed"),
    path('get-subscription-list', getSubscriptionList.as_view(), name="get-subscription-list"),
    path('model-private-feeds', modelPrivateFeed.as_view(), name="model-private-feeds"),
    path('report-reason', ListReportReason.as_view(), name="model-private-feeds"),
    path('add-report-reason', ReportReason.as_view(), name="report-reason"),
    path('save-tip', TipMeApi.as_view(), name="save-tip"),
    path('save-tip-finalized', TipMeApifinalize.as_view(), name="save-tip-finalized"),
    path('pay-out-history', PayOutHistory.as_view(), name="pay-out-history"),
   # path('get-top-ten-fans', GetTopTenFans.as_view(), name="get-top-ten-fans"),
   # path('total-revenue', TotalRevenue.as_view(), name="total-revenue"),
    path('model-profile-image', ModelProfileImages.as_view(), name="model-profile-image"),
    path('model-payment-details', ModelPaymentDetails.as_view(), name="model-payment-details"),
	path('get-payment-details', ModelPaymentDetails.as_view(), name="get-payment-details"),
    path('get-settings', ListSettings.as_view(), name="get-settings"),
    path('delete-account', DeleteAccount.as_view(), name="delete-account"),
    # path('users-subscribed-model', UsersSubscribedModel.as_view(), name="users-subscribed-model"),
    path('model-status-active', ModelSubscriptionStatusActive.as_view(), name="model-status-active"),
    path('model-deactive-status', ModelSubscriptionStatusDeactive.as_view(), name="model-deactive-status"),
    
    path('model-user-subscribe', ModelUserSubscribeGraph.as_view(), name='model-user-subscribe'),
    path('banner-image',BannerSlider.as_view(), name='banner-image'),
    path('get-ip', GetSystemIp.as_view(), name='ip-address'),
    path('unsubscribe-newsletter', unsubscribeNeswletter.as_view(), name='unsubscribe-newsletter'),
    path('forgot-password', ValidateforgotPassword.as_view(), name='forgot-password'),
    path('reset-password', ResetPassword.as_view(), name='reset-password'),
    path('text-block', BlockText.as_view(), name='text-block'),
    path('refer-slug', ReferSlugApi.as_view(), name='refer-slug'),
	path('payment-processing', PaymentProcessing.as_view(), name='payment-processing'),
    path('master-login', MasterLogin.as_view(), name='master-login'),
	path('faq', FaqText.as_view(), name='faq'),
	path('site-images', SiteContentImages.as_view(), name='site-images'),
	path('deactivate-account', DeActivateAccount.as_view(), name='deactivate-account'),
	path('edit-payment-method', EditPaymentMethodApi.as_view(), name='edit-payment-method'),
	path('get-new-expired-subscribers', NewExpiredSubscribers.as_view(), name='get-new-expired-subscribers'),
	path('add-main-profile-image', MainProfileImage.as_view(), name='add-main-profile-image'),
	path('check-private-feed', PrivateFeedEnable.as_view(), name='check-private-feed'),
	path('subscriber-following-models', followingList.as_view(), name="following-list"),
    path('subscriber-transaction-history', getUserTransactionList.as_view(), name="user-transaction-list"),
	path('subscriber-subscription-history', getUserSubscriptionPlanList.as_view(), name="user-subscription-plan"),
	path('subscriber-model-for-you', subscriberModelForYou.as_view(), name="subscriber-model-for-you"),
	path('cancelled-plan', cancelledPlan.as_view(), name="cancelledPlan"),
	
	
	path('model-verification-information', ModelVerificationInformation.as_view(), name='model-verification-information'),
	path('model-verification-images', ModelVerificationImages.as_view(), name='model-verification-images'),
	path('model-personal-information', ModelPersonalInformation.as_view(), name='model-personal-information'),
	path('update-model-subscription-plan', UpdateModelSubscriptionPlan.as_view(), name="update-model-subscription-plan"),
	path('update-model-profile-step-1', UpdateModelProfileStep1.as_view(), name="update-model-profile-step-1"),
	path('update-model-profile-step-2', UpdateModelProfileStep2.as_view(), name="update-model-profile-step-2"),
	

	
	
	
	##model dashboard api in view2
	path('model-dashboard-biggest-fan', modelDashboardBiggestFan.as_view(), name="modelDashboardBiggestFan"),
	path('model-dashboard-top-ten-biggest-fan', modelDashboardTopTenBiggestFan.as_view(), name="modelDashboardTopTenBiggestFan"),
	path('model-payout-history', modelPayoutHistory.as_view(), name="modelPayoutHistory"),
	path('model-transaction-history', modelTransactionHistory.as_view(), name="modelTransactionHistory"),
	
	path('model-active-subscribers', modelActiveSubscribers.as_view(), name="modelActiveSubscribers"),
	path('model-expired-subscribers', modelExpiredSubscribers.as_view(), name="modelExpiredSubscribers"),
	path('model-reported-subscribers', modelreportedSubscribers.as_view(), name="modelreportedSubscribers"),
	
	
	
	# path('model-subscribers-by-plan-type', modelSubscribersByPlanType.as_view(), name="modelSubscribersByPlanType"),
	path('model-new-expired-subscribers', modelNewExpiredSubscribers.as_view(), name="modelNewExpiredSubscribers"),
	path('model-revenue', modelRevenue.as_view(), name="modelRevenue"),
	path('model-subscriber-plan-list', modelSubscriberPlanList.as_view(), name="modelSubscriberPlanList"),
	path('model-basic-info', modelBasicInfo.as_view(), name="modelBasicInfo"),
	# path('model-analytics', modelAnalytics.as_view(), name="modelAnalytics"),
	
	path('model-split-data', modelSplitData.as_view(), name="modelSplitData"),
	path('is-flaged', isFlagedApi.as_view(), name="isFlagedApi"),
    path('list-revenue', ListRevenueGraph.as_view(), name="list-revenue"),
    path('model-profile-view', ModelProfileViewGraph.as_view(), name='model-profile-view'),
    path('new-expired-subscribers', NewExpiredSubscribersGraph.as_view(), name='new-expired-subscribers'),
    path('is-tick-marked', isTickMark.as_view(), name='is-tick-marked'),

    path('is-homepage-profile', HomepageProfileApi.as_view(), name='new-expired-subscribers'),
	##model dashboard api in view2
    path('is-homepage-profile', HomepageProfileApi.as_view(), name='new-expired-subscribers'),
    path('check-subscribed-plan-detail', CheckSubscribedPlanDetail.as_view(), name='check-subscribed-plan-detail'),
    
]
