# Generated by Django 2.2.5 on 2019-12-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_auto_20191211_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
