# Generated by Django 2.2.5 on 2020-02-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0003_sliderimage_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='order',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
